\documentclass[12pt]{article}

\usepackage{amsmath}
\usepackage{comment}
\usepackage{amscd}
\usepackage[utf8]{inputenc}
\usepackage{fancyhdr}
\usepackage{url}

\usepackage{calc}
%\usepackage{natbib}
\bibliographystyle{apalike}
\usepackage[american]{babel}

\setlength{\paperheight}{11in}
\setlength{\paperwidth}{8.5in}
\addtolength{\voffset}{-1.0in}
\addtolength{\hoffset}{-1.0in}
\setlength{\topmargin}{1in}
\setlength{\oddsidemargin}{1in}
\setlength{\evensidemargin}{1in}
\setlength{\textwidth}{\paperwidth - 2in}
\setlength{\textheight}{\paperheight - 2in}
\setlength{\footskip}{36pt}
\setlength{\marginparsep}{0.5cm}
\setlength{\marginparwidth}{1.5cm}
\setlength{\headheight}{0pt}
\setlength{\headsep}{0pt}



\pagestyle{fancy}
\renewcommand{\headrulewidth}{0pt}
\lhead{}
\chead{}
\rhead{}
\lfoot{}
\cfoot{\thepage}
\rfoot{}

\SweaveOpts{keep.source=FALSE}

\begin{document}
%\VignetteIndexEntry{phylomap_DIC_small_tree}
<<echo=FALSE>>=
options(width=74, continue=" ")
@

\begin{center}
  {\LARGE DIC Model Selection using Phylomap on a 70 Tip Tree}\\\ \\
  {Jan Irvahn$^1$ and Vladimir N. Minin$^2$ \\ 
    $^1$Pacific Northwest National Laboratory, Richland, WA, 99354, USA\\
    $^2$Department of Statistics, University of Washington Seattle, WA, 98195, USA
  }
\end{center}

This tutorial shows how to use the R package phylomap to calculate DIC, deviance information criterion, for a tree with 70 tips. To get started, install the phylomap R package from GitHub. 
\begin{verbatim}
> install.packages("devtools")
> library(devtools)
> install_github("phylomap")
\end{verbatim}

Start R and load the needed libraries. 
<<one>>=
library(phylomap)
library(corHMM)
library(expm)
@

Import the Cephalopod phylogenies and simulate data from a 2 state model ten times.
<<two>>=
cephalopodTrees = read.tree(file=
system.file("extdata/Cephalopod/BLsonboots70.phy"
,package="phylomap"))
atree<-cephalopodTrees[[1]]
cephalopodTraits = read.csv(file=
system.file("extdata/Cephalopod/BLspecies70.csv",
package="phylomap"),header=FALSE)
tip.num = dim(cephalopodTraits)[1]
cephalopodTraitVec = numeric(tip.num)
tipNames = as.character(cephalopodTraits[,1])
cephalopodTraitVec = cephalopodTraits[,2]
names(cephalopodTraitVec) = tipNames
branchcount<-length(atree$edge.length)
atree$maps<-list()
for(i in 1:length(atree$edge.length)) {
 atree$maps[[i]]<-atree$edge.length[i]
 names(atree$maps[[i]])<-1
}
tipstates<-rep(-10,length(atree$tip.label))
for(i in 1:length(atree$tip.label)) {
 for(j in 1:length(cephalopodTraitVec)) {
  if(atree$tip.label[i]==names(cephalopodTraitVec)[j]) tipstates[i]<-cephalopodTraitVec[j]+1
 }
}
atree$states<-tipstates
atree$node.states<-matrix(rep(1,branchcount*2),nrow=branchcount)
for(j in 1:length(atree$tip.label)) {
 row<-1
 while(j!=atree$edge[row,2]) row<-row+1
 atree$maps[[row]]<-rep(atree$edge.length[row]/2,2)
 names(atree$maps[[row]])<-c(1,tipstates[j])
}
atree$mapnames<-list()
for(i in 1:length(atree$maps)) atree$mapnames[[i]]<-as.integer(names(atree$maps[[i]]))
for(i in 1:branchcount) if(atree$edge[i,2]<=70) atree$node.states[i,2]<-tipstates[atree$edge[i,2]]
atree<-makemapnames(atree)
Q2<-matrix(c(-.22,.67,.22,-.67),nrow=2)
pid2<-c(0,1)
sampledata2<-NULL
set.seed(103)
for(i in 1:10) sampledata2<-rbind(sampledata2,sample2statehistory(atree,Q2,pid2))
@

Create ten phylogenies with the simulated tip states.
<<three>>=
data12<-sampledata2[1,c(1:139)]   
data22<-sampledata2[2,c(1:139)]   
data32<-sampledata2[3,c(1:139)]   
data42<-sampledata2[4,c(1:139)]   
data52<-sampledata2[5,c(1:139)]   
data62<-sampledata2[6,c(1:139)]   
data72<-sampledata2[7,c(1:139)]   
data82<-sampledata2[8,c(1:139)]  
data92<-sampledata2[9,c(1:139)]  
data102<-sampledata2[10,c(1:139)]

atree12<-changemytipstates(data12,atree)
atree22<-changemytipstates(data22,atree)
atree32<-changemytipstates(data32,atree)
atree42<-changemytipstates(data42,atree)
atree52<-changemytipstates(data52,atree)
atree62<-changemytipstates(data62,atree)
atree72<-changemytipstates(data72,atree)
atree82<-changemytipstates(data82,atree)
atree92<-changemytipstates(data92,atree)
atree102<-changemytipstates(data102,atree)
@
 
Simulate data from a 4 state model ten times, creating ten phylogenies.
<<four>>=
Q<-make2sQ(.1,.1,.2,.2,10) 
pid<-c(0,0.5,0,0.5)
sampledata4<-NULL
set.seed(102)
for(i in 1:10) sampledata4<-rbind(sampledata4,sample2statehistory(atree,Q,pid))
data14<-sampledata4[1,c(1:139)]   
data24<-sampledata4[2,c(1:139)]   
data34<-sampledata4[3,c(1:139)]   
data44<-sampledata4[4,c(1:139)]   
data54<-sampledata4[5,c(1:139)]   
data64<-sampledata4[6,c(1:139)]   
data74<-sampledata4[7,c(1:139)]   
data84<-sampledata4[8,c(1:139)]   
data94<-sampledata4[9,c(1:139)]   
data104<-sampledata4[10,c(1:139)] 
atree14<-changemytipstates(data14,atree)
atree24<-changemytipstates(data24,atree)
atree34<-changemytipstates(data34,atree)
atree44<-changemytipstates(data44,atree)
atree54<-changemytipstates(data54,atree)
atree64<-changemytipstates(data64,atree)
atree74<-changemytipstates(data74,atree)
atree84<-changemytipstates(data84,atree)
atree94<-changemytipstates(data94,atree)
atree104<-changemytipstates(data104,atree)
@ 

Set up starting transition matrices and priors for the 2 state and 4 state models.
<<five>>=
Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
pid2<-c(0,1)

prior2r<-c(.55,1,.55,1)
prior2d<-c(1,.1,1,.1)
prior2s<-c(.01,.01,.01,.01)
N<-10000
Omega2<-10
Q4<-make2sQ(.1,.1,.2,.2,10) 
pid4<-c(0,0.5,0,0.5)
prior4r<-c(1,10,2,10,20,2)
prior4d<-c(1,.1,1,.1,1,.1)
prior4s<-c(.01,.01,.01,.01,.01,.01)
N<-10000
Omega4<-10
# Matrix to keep track of the number of times DIC gets it right
# row 1: true model is 2 state
# row 2: true model is 4 state
# columns 1, 2, and 3 correspond to priors r, d, and s
DIC_win_count_fixed_root<-matrix(rep(0,6),nrow=2)
@

Generate summary statistics for the posterior distribution of state histories and model parameters when the root is fixed in state 2 (slow or fast in the 4 state scenario). 
<<six>>=
########################
######################## Simulation Set 1
########################
########################
#### tree2
Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree12,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")
Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree12,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")
Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree12,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")
Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree12,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")
Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree12,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")
Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree12,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")
#### tree4
Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree14,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")
Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree14,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")
Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree14,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")
Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree14,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")
Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree14,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")
Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree14,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")
###
### DIC comparisons
###
DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)
DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree12,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree12,pid4)
DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree12,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree12,pid4)
DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree12,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree12,pid4)
DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree14,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree14,pid4)
DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree14,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree14,pid4)
DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree14,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree14,pid4)
DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])
########################
######################## Simulation Set 2
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree22,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree22,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree22,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree22,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree22,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree22,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree24,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree24,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree24,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree24,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree24,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree24,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree22,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree22,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree22,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree22,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree22,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree22,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree24,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree24,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree24,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree24,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree24,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree24,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])


########################
######################## Simulation Set 3
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree32,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree32,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree32,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree32,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree32,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree32,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree34,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree34,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree34,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree34,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree34,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree34,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree32,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree32,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree32,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree32,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree32,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree32,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree34,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree34,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree34,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree34,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree34,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree34,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])


########################
######################## Simulation Set 4
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree42,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree42,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree42,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree42,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree42,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree42,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree44,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree44,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree44,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree44,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree44,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree44,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree42,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree42,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree42,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree42,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree42,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree42,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree44,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree44,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree44,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree44,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree44,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree44,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])

########################
######################## Simulation Set 5
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree52,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree52,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree52,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree52,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree52,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree52,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree54,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree54,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree54,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree54,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree54,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree54,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree52,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree52,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree52,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree52,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree52,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree52,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree54,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree54,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree54,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree54,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree54,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree54,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])

########################
######################## Simulation Set 6
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree62,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree62,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree62,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree62,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree62,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree62,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree64,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree64,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree64,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree64,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree64,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree64,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree62,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree62,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree62,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree62,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree62,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree62,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree64,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree64,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree64,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree64,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree64,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree64,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])

########################
######################## Simulation Set 7
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree72,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree72,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree72,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree72,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree72,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree72,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree74,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree74,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree74,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree74,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree74,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree74,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree72,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree72,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree72,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree72,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree72,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree72,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree74,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree74,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree74,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree74,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree74,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree74,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])

########################
######################## Simulation Set 8
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree82,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree82,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree82,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree82,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree82,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree82,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree84,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree84,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree84,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree84,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree84,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree84,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree82,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree82,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree82,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree82,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree82,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree82,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree84,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree84,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree84,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree84,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree84,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree84,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])

########################
######################## Simulation Set 9
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree92,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree92,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree92,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree92,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree92,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree92,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree94,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree94,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree94,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree94,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree94,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree94,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree92,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree92,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree92,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree92,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree92,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree92,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree94,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree94,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree94,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree94,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree94,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree94,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])

########################
######################## Simulation Set 10
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree102,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree102,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree102,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree102,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree102,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree102,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree104,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree104,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree104,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree104,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree104,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree104,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree102,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree102,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree102,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree102,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree102,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree102,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree104,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree104,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree104,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree104,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree104,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree104,pid4)

DIC_win_count_fixed_root[1,]<-DIC_win_count_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_fixed_root[2,]<-DIC_win_count_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])
@

Generate summary statistics for the posterior distribution of state histories and model parameters when the root is not fixed. 

<<seven>>=
Q2<-matrix(c(-.22,.67,.22,-.67),nrow=2)
pid2<-c(0.5,0.5)
sampledata2<-NULL

set.seed(100)

for(i in 1:10) {
 sampledata2<-rbind(sampledata2,sample2statehistory(atree,Q2,pid2))
 cat(i,"\r")
}

data12<-sampledata2[1,c(1:139)]   # 0 `true' trait gains  sampledata2[,140]
data22<-sampledata2[2,c(1:139)]   # 0 `true' trait gains
data32<-sampledata2[3,c(1:139)]   # 0 `true' trait gains
data42<-sampledata2[4,c(1:139)]   # 2 `true' trait gains
data52<-sampledata2[5,c(1:139)]   # 4 `true' trait gains
data62<-sampledata2[6,c(1:139)]   # 1 `true' trait gains
data72<-sampledata2[7,c(1:139)]   # 2 `true' trait gains
data82<-sampledata2[8,c(1:139)]   # 1 `true' trait gains
data92<-sampledata2[9,c(1:139)]   # 2 `true' trait gains
data102<-sampledata2[10,c(1:139)] # 3 `true' trait gains


atree12<-changemytipstates(data12,atree)
atree22<-changemytipstates(data22,atree)
atree32<-changemytipstates(data32,atree)
atree42<-changemytipstates(data42,atree)
atree52<-changemytipstates(data52,atree)
atree62<-changemytipstates(data62,atree)
atree72<-changemytipstates(data72,atree)
atree82<-changemytipstates(data82,atree)
atree92<-changemytipstates(data92,atree)
atree102<-changemytipstates(data102,atree)

Q<-make2sQ(.1,.1,.2,.2,10) 
pid<-c(0.25,0.25,0.25,0.25)
sampledata4<-NULL

set.seed(100)

for(i in 1:10) {
 sampledata4<-rbind(sampledata4,sample2statehistory(atree,Q,pid))
 cat(i,"\r")
}

data14<-sampledata4[1,c(1:139)]   # 3 `true' trait gains  sampledata4[,140]
data24<-sampledata4[2,c(1:139)]   # 1 `true' trait gains
data34<-sampledata4[3,c(1:139)]   # 6 `true' trait gains
data44<-sampledata4[4,c(1:139)]   # 4 `true' trait gains
data54<-sampledata4[5,c(1:139)]   # 0 `true' trait gains
data64<-sampledata4[6,c(1:139)]   # 1 `true' trait gains
data74<-sampledata4[7,c(1:139)]   # 1 `true' trait gains
data84<-sampledata4[8,c(1:139)]   # 1 `true' trait gains
data94<-sampledata4[9,c(1:139)]   # 3 `true' trait gains
data104<-sampledata4[10,c(1:139)] # 8 `true' trait gains


atree14<-changemytipstates(data14,atree)
atree24<-changemytipstates(data24,atree)
atree34<-changemytipstates(data34,atree)
atree44<-changemytipstates(data44,atree)
atree54<-changemytipstates(data54,atree)
atree64<-changemytipstates(data64,atree)
atree74<-changemytipstates(data74,atree)
atree84<-changemytipstates(data84,atree)
atree94<-changemytipstates(data94,atree)
atree104<-changemytipstates(data104,atree)

########################
########################
########################
########################

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
pid2<-c(0.5,0.5)

prior2r<-c(.55,1,.55,1)
prior2d<-c(1,.1,1,.1)
prior2s<-c(.01,.01,.01,.01)
N<-10000
Omega2<-10

Q4<-make2sQ(.1,.1,.2,.2,10) 
pid4<-c(0.25,0.25,0.25,0.25)
prior4r<-c(1,10,2,10,20,2)
prior4d<-c(1,.1,1,.1,1,.1)
prior4s<-c(.01,.01,.01,.01,.01,.01)
N<-10000
Omega4<-10

########################
########################
########################
########################

# row 1: true model is 2 state
# row 2: true model is 4 state
# columns 1, 2, and 3 correspond to priors r, d, and s

DIC_win_count_not_fixed_root<-matrix(rep(0,6),nrow=2)


########################
######################## Simulation Set 1
########################
########################

#### tree2

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree12,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree12,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree12,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree12,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree12,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree12,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree14,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree14,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree14,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree14,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree14,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree14,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree12,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree12,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree12,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree12,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree12,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree12,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree14,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree14,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree14,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree14,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree14,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree14,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])



########################
######################## Simulation Set 2
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree22,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree22,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree22,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree22,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree22,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree22,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree24,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree24,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree24,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree24,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree24,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree24,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###

DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree22,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree22,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree22,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree22,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree22,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree22,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree24,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree24,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree24,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree24,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree24,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree24,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])



########################
######################## Simulation Set 3
########################
########################

#### tree2


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree32,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree32,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree32,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree32,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree32,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree32,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree34,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree34,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree34,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree34,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree34,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree34,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###


DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree32,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree32,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree32,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree32,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree32,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree32,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree34,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree34,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree34,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree34,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree34,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree34,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])


########################
######################## Simulation Set 4
########################
########################


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree42,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree42,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree42,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree42,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree42,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree42,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree44,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree44,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree44,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree44,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree44,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree44,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###


DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree42,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree42,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree42,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree42,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree42,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree42,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree44,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree44,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree44,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree44,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree44,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree44,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])



########################
######################## Simulation Set 5
########################
########################


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree52,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree52,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree52,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree52,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree52,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree52,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree54,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree54,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree54,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree54,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree54,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree54,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###


DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree52,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree52,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree52,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree52,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree52,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree52,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree54,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree54,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree54,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree54,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree54,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree54,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])



########################
######################## Simulation Set 6
########################
########################


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree62,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree62,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree62,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree62,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree62,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree62,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree64,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree64,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree64,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree64,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree64,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree64,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###


DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree62,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree62,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree62,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree62,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree62,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree62,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree64,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree64,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree64,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree64,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree64,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree64,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])



########################
######################## Simulation Set 7
########################
########################


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree72,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree72,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree72,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree72,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree72,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree72,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree74,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree74,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree74,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree74,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree74,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree74,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###



DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree72,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree72,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree72,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree72,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree72,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree72,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree74,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree74,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree74,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree74,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree74,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree74,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])


########################
######################## Simulation Set 8
########################
########################


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree82,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree82,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree82,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree82,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree82,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree82,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree84,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree84,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree84,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree84,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree84,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree84,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###



DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree82,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree82,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree82,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree82,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree82,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree82,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree84,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree84,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree84,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree84,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree84,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree84,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])


########################
######################## Simulation Set 9
########################
########################


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree92,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree92,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree92,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree92,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree92,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree92,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree94,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree94,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree94,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree94,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree94,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree94,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###



DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree92,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree92,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree92,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree92,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree92,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree92,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree94,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree94,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree94,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree94,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree94,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree94,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])



########################
######################## Simulation Set 10
########################
########################


Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstr<-sumstatMCMC2sDICt(atree102,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtstr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtstd<-sumstatMCMC2sDICt(atree102,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtstd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsts<-sumstatMCMC2sDICt(atree102,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsts)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstr<-sumstatMCMCksDICt(atree102,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfstr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfstd<-sumstatMCMCksDICt(atree102,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfstd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10) 
SIMfsts<-sumstatMCMCksDICt(atree102,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsts)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

#### tree4

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfr<-sumstatMCMC2sDICt(atree104,Q2,pid2,Omega2,N,prior2r)
colnames(SIMtsfr)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfd<-sumstatMCMC2sDICt(atree104,Q2,pid2,Omega2,N,prior2d)
colnames(SIMtsfd)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q2<-matrix(c(-.1,.1,.1,-.1),nrow=2)
SIMtsfs<-sumstatMCMC2sDICt(atree104,Q2,pid2,Omega2,N,prior2s)
colnames(SIMtsfs)<-c("t0","t1","n00","n01","n10","n11","l01","l10","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfr<-sumstatMCMCksDICt(atree104,Q4,pid4,Omega4,N,prior4r)
colnames(SIMfsfr)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfd<-sumstatMCMCksDICt(atree104,Q4,pid4,Omega4,N,prior4d)
colnames(SIMfsfd)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

Q4<-make2sQ(.1,.1,.2,.2,10)
SIMfsfs<-sumstatMCMCksDICt(atree104,Q4,pid4,Omega4,N,prior4s)
colnames(SIMfsfs)<-c("t1","t2","t3","t4","n11","n12","n13","n14","n21","n22","n23","n24","n31","n32","n33","n34","n41","n42","n43","n44","l01","l10","k01","k10","gamma","root_state","log(p(y|Q))")

###
### DIC comparisons
###


DICtree2<-matrix(rep(0,6),nrow=2)
DICtree4<-matrix(rep(0,6),nrow=2)

DICtree2[1,1]<-make2stateDIC(SIMtstr[-c(1:1000),],atree102,pid2)
DICtree2[2,1]<-make4stateDIC(SIMfstr[-c(1:1000),],atree102,pid4)

DICtree2[1,2]<-make2stateDIC(SIMtstd[-c(1:1000),],atree102,pid2)
DICtree2[2,2]<-make4stateDIC(SIMfstd[-c(1:1000),],atree102,pid4)

DICtree2[1,3]<-make2stateDIC(SIMtsts[-c(1:1000),],atree102,pid2)
DICtree2[2,3]<-make4stateDIC(SIMfsts[-c(1:1000),],atree102,pid4)


DICtree4[1,1]<-make2stateDIC(SIMtsfr[-c(1:1000),],atree104,pid2)
DICtree4[2,1]<-make4stateDIC(SIMfsfr[-c(1:1000),],atree104,pid4)

DICtree4[1,2]<-make2stateDIC(SIMtsfd[-c(1:1000),],atree104,pid2)
DICtree4[2,2]<-make4stateDIC(SIMfsfd[-c(1:1000),],atree104,pid4)

DICtree4[1,3]<-make2stateDIC(SIMtsfs[-c(1:1000),],atree104,pid2)
DICtree4[2,3]<-make4stateDIC(SIMfsfs[-c(1:1000),],atree104,pid4)

DIC_win_count_not_fixed_root[1,]<-DIC_win_count_not_fixed_root[1,]+as.numeric(DICtree2[1,]<DICtree2[2,])
DIC_win_count_not_fixed_root[2,]<-DIC_win_count_not_fixed_root[2,]+as.numeric(DICtree4[2,]<DICtree4[1,])
@

<<eight>>=
library(corHMM)

traitmate12<-data.frame(atree12$tip.label,as.integer(atree12$state-1))
names(traitmate12)<-c("species","T1")

one.cat12 <- corHMM(atree12,traitmate12,rate.cat=1,node.states="marginal", ip=1)
two.cat12 <- corHMM(atree12,traitmate12,rate.cat=2,node.states="marginal", ip=1) 

traitmate22<-data.frame(atree22$tip.label,as.integer(atree22$state-1))
names(traitmate22)<-c("species","T1")

one.cat22 <- corHMM(atree22,traitmate22,rate.cat=1,node.states="marginal", ip=1)
two.cat22 <- corHMM(atree22,traitmate22,rate.cat=2,node.states="marginal", ip=1) 

traitmate32<-data.frame(atree32$tip.label,as.integer(atree32$state-1))
names(traitmate32)<-c("species","T1")

one.cat32 <- corHMM(atree32,traitmate32,rate.cat=1,node.states="marginal", ip=1)
two.cat32 <- corHMM(atree32,traitmate32,rate.cat=2,node.states="marginal", ip=1) 

traitmate42<-data.frame(atree42$tip.label,as.integer(atree42$state-1))
names(traitmate42)<-c("species","T1")

one.cat42 <- corHMM(atree42,traitmate42,rate.cat=1,node.states="marginal", ip=1)
two.cat42 <- corHMM(atree42,traitmate42,rate.cat=2,node.states="marginal", ip=1) 

traitmate52<-data.frame(atree52$tip.label,as.integer(atree52$state-1))
names(traitmate52)<-c("species","T1")

one.cat52 <- corHMM(atree52,traitmate52,rate.cat=1,node.states="marginal", ip=1)
two.cat52 <- corHMM(atree52,traitmate52,rate.cat=2,node.states="marginal", ip=1) 

traitmate62<-data.frame(atree62$tip.label,as.integer(atree62$state-1))
names(traitmate62)<-c("species","T1")

one.cat62 <- corHMM(atree62,traitmate62,rate.cat=1,node.states="marginal", ip=1)
two.cat62 <- corHMM(atree62,traitmate62,rate.cat=2,node.states="marginal", ip=1) 

traitmate72<-data.frame(atree72$tip.label,as.integer(atree72$state-1))
names(traitmate72)<-c("species","T1")

one.cat72 <- corHMM(atree72,traitmate72,rate.cat=1,node.states="marginal", ip=1)
two.cat72 <- corHMM(atree72,traitmate72,rate.cat=2,node.states="marginal", ip=1) 

traitmate82<-data.frame(atree82$tip.label,as.integer(atree82$state-1))
names(traitmate82)<-c("species","T1")

one.cat82 <- corHMM(atree82,traitmate82,rate.cat=1,node.states="marginal", ip=1)
two.cat82 <- corHMM(atree82,traitmate82,rate.cat=2,node.states="marginal", ip=1) 

traitmate92<-data.frame(atree92$tip.label,as.integer(atree92$state-1))
names(traitmate92)<-c("species","T1")

one.cat92 <- corHMM(atree92,traitmate92,rate.cat=1,node.states="marginal", ip=1)
two.cat92 <- corHMM(atree92,traitmate92,rate.cat=2,node.states="marginal", ip=1) 

traitmate102<-data.frame(atree102$tip.label,as.integer(atree102$state-1))
names(traitmate102)<-c("species","T1")

one.cat102 <- corHMM(atree102,traitmate102,rate.cat=1,node.states="marginal", ip=1)
two.cat102 <- corHMM(atree102,traitmate102,rate.cat=2,node.states="marginal", ip=1) 




one.cat12$AIC
two.cat12$AIC

one.cat22$AIC
two.cat22$AIC

one.cat32$AIC
two.cat32$AIC

one.cat42$AIC
two.cat42$AIC

one.cat52$AIC
two.cat52$AIC

one.cat62$AIC
two.cat62$AIC

one.cat72$AIC
two.cat72$AIC

one.cat82$AIC
two.cat82$AIC

one.cat92$AIC
two.cat92$AIC

one.cat102$AIC
two.cat102$AIC





traitmate14<-data.frame(atree14$tip.label,as.integer(atree14$state-1))
names(traitmate14)<-c("species","T1")

one.cat14 <- corHMM(atree14,traitmate14,rate.cat=1,node.states="marginal", ip=1)
two.cat14 <- corHMM(atree14,traitmate14,rate.cat=2,node.states="marginal", ip=1) 

traitmate24<-data.frame(atree24$tip.label,as.integer(atree24$state-1))
names(traitmate24)<-c("species","T1")

one.cat24 <- corHMM(atree24,traitmate24,rate.cat=1,node.states="marginal", ip=1)
two.cat24 <- corHMM(atree24,traitmate24,rate.cat=2,node.states="marginal", ip=1) 

traitmate34<-data.frame(atree34$tip.label,as.integer(atree34$state-1))
names(traitmate34)<-c("species","T1")

one.cat34 <- corHMM(atree34,traitmate34,rate.cat=1,node.states="marginal", ip=1)
two.cat34 <- corHMM(atree34,traitmate34,rate.cat=2,node.states="marginal", ip=1) 

traitmate44<-data.frame(atree44$tip.label,as.integer(atree44$state-1))
names(traitmate44)<-c("species","T1")

one.cat44 <- corHMM(atree44,traitmate44,rate.cat=1,node.states="marginal", ip=1)
two.cat44 <- corHMM(atree44,traitmate44,rate.cat=2,node.states="marginal", ip=1) 

traitmate54<-data.frame(atree54$tip.label,as.integer(atree54$state-1))
names(traitmate54)<-c("species","T1")

one.cat54 <- corHMM(atree54,traitmate54,rate.cat=1,node.states="marginal", ip=1)
two.cat54 <- corHMM(atree54,traitmate54,rate.cat=2,node.states="marginal", ip=1) 

traitmate64<-data.frame(atree64$tip.label,as.integer(atree64$state-1))
names(traitmate64)<-c("species","T1")

one.cat64 <- corHMM(atree64,traitmate64,rate.cat=1,node.states="marginal", ip=1)
two.cat64 <- corHMM(atree64,traitmate64,rate.cat=2,node.states="marginal", ip=1) 

traitmate74<-data.frame(atree74$tip.label,as.integer(atree74$state-1))
names(traitmate74)<-c("species","T1")

one.cat74 <- corHMM(atree74,traitmate74,rate.cat=1,node.states="marginal", ip=1)
two.cat74 <- corHMM(atree74,traitmate74,rate.cat=2,node.states="marginal", ip=1) 

traitmate84<-data.frame(atree84$tip.label,as.integer(atree84$state-1))
names(traitmate84)<-c("species","T1")

one.cat84 <- corHMM(atree84,traitmate84,rate.cat=1,node.states="marginal", ip=1)
two.cat84 <- corHMM(atree84,traitmate84,rate.cat=2,node.states="marginal", ip=1) 

traitmate94<-data.frame(atree94$tip.label,as.integer(atree94$state-1))
names(traitmate94)<-c("species","T1")

one.cat94 <- corHMM(atree94,traitmate94,rate.cat=1,node.states="marginal", ip=1)
two.cat94 <- corHMM(atree94,traitmate94,rate.cat=2,node.states="marginal", ip=1) 

traitmate104<-data.frame(atree104$tip.label,as.integer(atree104$state-1))
names(traitmate104)<-c("species","T1")

one.cat104 <- corHMM(atree104,traitmate104,rate.cat=1,node.states="marginal", ip=1)
two.cat104 <- corHMM(atree104,traitmate104,rate.cat=2,node.states="marginal", ip=1) 


TP_count_2<-0
TP_count_4<-0
for(i in 1:10) {
 o2<-get(paste(paste("one.cat",i,sep=""),"2",sep=""))
 t2<-get(paste(paste("two.cat",i,sep=""),"2",sep=""))
 o4<-get(paste(paste("one.cat",i,sep=""),"4",sep=""))
 t4<-get(paste(paste("two.cat",i,sep=""),"4",sep=""))
 if(o2$AIC < t2$AIC) TP_count_2<-TP_count_2+1
 if(t4$AIC < o4$AIC) TP_count_2<-TP_count_2+1
}
@


Plot the results.

<<nine>>=
<<label=rplot,include=FALSE>>=
par(mar=c(6.1,4.1,4.1,2.1))
plot(0,0,xlab="",xlim=c(1,4),ylim=c(0,10),xaxt="n",ylab="number of true positives",pch=16,col="white",main="Model Selection Results: 70 Tip Tree",yaxt="n",cex.axis=2,cex.lab=2,cex.main=2)

abline(h=c(0:10),col="lightgrey")
axis(1, at=c(1,2,3,4),labels=c("DIC","DIC","DIC","AIC"), las=1,cex.axis=1.8)
axis(1, at=c(1,2,3,4),labels=c("    restricted"," diffuse","spike",""),pos=-1.1, las=1,cex.axis=1.8,tick=FALSE)
axis(1, at=c(1,2,3,4),labels=c("priors","priors"," priors",""),pos=-1.6, las=1,cex.axis=1.8,tick=FALSE)

axis(2, at=c(0:10),labels=c(0:10), las=1,cex=2)

points(c(1,2,3,4)-.04,c(DIC_win_count_not_fixed_root[1,],TP_count_2),col="blue",pch=16,cex=2)
points(c(1,2,3,4)-.04,c(DIC_win_count_not_fixed_root[2,],TP_count_4),col="blue",pch=17,cex=2)

points(c(1,2,3)+.04,DIC_win_count_fixed_root[1,],pch=16,col="red",cex=2)
points(c(1,2,3)+.04,DIC_win_count_fixed_root[2,],col="red",pch=17,cex=2)

text(1.3,4.5,"root free",col="blue",cex=2)
arrows(1.68,4.4,1.95,2.3,lwd=2,col="blue")
arrows(1.68,4.6,2.85,2.05,lwd=2,col="blue")


text(1.3,0,"root fixed",col="red",cex=2)
arrows(1.7,0.1,1.95,.8,lwd=2,col="red")
arrows(1.7,-0.1,2.95,.8,lwd=2,col="red")

text(3.6,7.4,"true model:",cex=2)
text(3.6,6.6,"2-state",cex=2)
arrows(3.65,7.6,3.03,8.87,lwd=2,col="blue")
arrows(3.7,7.6,3.1,9.8,lwd=2,col="red")

text(3.6,4.4,"true model:",cex=2)
text(3.6,3.6,"4-state",cex=2)
arrows(3.48,3.1,3.1,1.15,lwd=2,col="red")
arrows(3.52,3.1,3.9,0.15,lwd=2,col="blue")
@
\begin{figure}[!t]
 \centering
<<label=rplot,fig=TRUE,echo=FALSE,height=9,width=9>>=
<<rplot>>
@
\caption{Model selection results for simulated data on a 70 tip tree. We simulated 40 data sets from 4 different models, ten from a 2-state model of evolution with the root fixed in state 1 (red circles), ten from a 4-state model of evolution with the root fixed in state 1 (red triangles), ten from a 2-state model of evolution with the root not fixed (blue circles), and ten from a 4-state model of evolution with the root not fixed (blue triangles). The number of times each model selection procedure selected the correct model is plotted on the y-axis. We analyzed all 40 data sets with DIC using three different priors and we analyzed the 20 data sets with the root not fixed using corHMM's AIC. }
\label{Rplot}
\end{figure}



%\bibliography{phylomap_tutorial}

\begin{thebibliography}{apalike}
\bibitem{fitzjohn2012diversitree} FitzJohn, Richard G (2012) Diversitree: comparative phylogenetic analyses of diversification in R. {\em Methods in Ecology and Evolution}, {\bf 3}, 1084-1092.
\bibitem{sipos2011phylosim} Sipos {\em et al.} (2005) PhyloSim-Monte Carlo simulation of sequence evolution in the R statistical computing environment. {\em BMC bioinformatics}, {\bf 12}, 104.
\end{thebibliography}


\end{document}

