# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SPARSEmaketreelistMCMC <- function(x, Q, pid, B, Omega, nen, nodelist, root, N) {
    .Call('phylomap_SPARSEmaketreelistMCMC', PACKAGE = 'phylomap', x, Q, pid, B, Omega, nen, nodelist, root, N)
}

maketreelistMCMC <- function(x, Q, pid, B, Omega, nen, nodelist, root, N) {
    .Call('phylomap_maketreelistMCMC', PACKAGE = 'phylomap', x, Q, pid, B, Omega, nen, nodelist, root, N)
}

maketreelistEXP <- function(x, Q, pid, nen, nodelist, root, N, lefts, rights, d) {
    .Call('phylomap_maketreelistEXP', PACKAGE = 'phylomap', x, Q, pid, nen, nodelist, root, N, lefts, rights, d)
}

#
# rate matrix uncertain
#

maketreelistMCMCbf <- function(x,Q,pid,B,Omega,nen,nodelist,root,N,prior) {
    .Call('phylomap_maketreelistMCMCbf', PACKAGE = 'phylomap', x,Q,pid,B,Omega,nen,nodelist,root,N,prior)
}

maketreelistMCMCks <- function(x,Q,pid,B,Omega,nen,nodelist,root,N,prior) {
    .Call('phylomap_maketreelistMCMCks', PACKAGE = 'phylomap', x,Q,pid,B,Omega,nen,nodelist,root,N,prior)
}
